mmenu.settings:
  type: mapping
  label: 'MMenu Settings'
  mapping:
    mmenu_allowed_blocks_nums:
      type: integer
      label: 'Block Count'
    langcode:
      type: string
      label: 'Default language'
